### PR TITLE
adding more metrics

### PR DESCRIPTION
**Pull request by wei-lee**
JIRA:

https://issues.redhat.com/browse/DEL-266

To verify:

1. Check out the branch and run `make deploy`
3. Change the image of workload to use the `dev` tag rather than the `master` tag
2. Wait for a while and then check grafana (the RHMI one), there should be a new dashboard called `workload-web-app`. You should be able to view the dashboard and see some data.

Or check the one that's deployed here: https://grafana-route-redhat-rhmi-middleware-monitoring-operator.apps.weili.j0c0.s1.devshift.org/d/omfjL5mGk/workload-app?orgId=1&refresh=10s&from=now-3h&to=now. (ping me for credential)

### CODE REVIEW

**Comment by b1zzu** [comment]
:eyes:

**Comment by STEPHINRACHEL** [comment]
Followed the verification steps and able to view the workload-web-app grafana dashboard with some data
Screenshot 2020-06-08 at 17 31 07

**Comment by b1zzu** [comment]
@STEPHINRACHEL @wei-lee the 3scale is showing a downtime because the deployment.sh is not waiting for the api endpoint to be available, is it fine? or should we wait for it before to avoid viewing the downtime?

**Comment by wei-lee** [comment]
@b1zzu if we can figure out a good way to do it, then yes let's update the script to wait for it to be ready. But it can be done in a separate PR. Let's merge this one first. If you are happy with the changes, @b1zzu @STEPHINRACHEL can you approve the PR?

**Pull request merged**
