### PR TITLE
Increase replicas, add podDisruptionBugdet and topologySpreadConstraints

### PR DESCRIPTION
**Pull request by austincunningham**
## What
increase replicas, add podDisruptionBugdet and topologySpreadConstraints
## Verification
- deploy managed api on a multi az cluster
- checkout this branch 
- set the env
```bash   
export RHOAM=true
export GRAFANA_DASHBOARD=true

```
- run `make local\deploy`
- check that there are two pods for the workload-web-app
- Check that the pods are on different AZ using integreatly-operator/scripts/podsAz.sh  e.g.                                                                                        
```bash
./podsAz.sh workload-web-app           
Pods distribution for 'workload-web-app'
| Pod name | Availability Zone |
| -------- | ----------------- |
| workload-web-app-1-7hwrm | eu-west-1a |
| workload-web-app-1-deploy | eu-west-1c |
| workload-web-app-1-r9bcc | eu-west-1c |
```
- check that there is a podDisruptionBugdet
```bash
oc get podDistruptionBugdet --namespace workload-web-app
```
- run `make local\undeploy` to uninstall and confirm removed

### CODE REVIEW

**Comment by psturc** [comment]
👀

**Comment by psturc** [comment]
@austincunningham when I run wwa locally from this branch against RHOAM cluster, it tries to create AMQ resources.
```
Creating required AMQ resources
error: unable to recognize "/workload-web-app/deploy/amq/auth.yaml": no matches for kind "AuthenticationService" in version "admin.enmasse.io/v1beta1"
error: unable to recognize "/workload-web-app/deploy/amq/addressspace.yaml": no matches for kind "AddressSpace" in version "enmasse.io/v1beta1"
error: unable to recognize "/workload-web-app/deploy/amq/address.yaml": no matches for kind "Address" in version "enmasse.io/v1beta1"
Waiting for AMQ AddressSpace to be ready
Waiting for Addressspace is ready for 5m...
error: the server doesn't have a resource type "addressspace"
Waiting for Addressspace is ready... Trying again in 10s
error: the server doesn't have a resource type "addressspace"
```
should we skip the AMQ part when deploying it against RHOAM cluster?

**Comment by austincunningham** [comment]
@psturc as discussed previously we can add an extra target for RHOAM like v1 of rhmi https://github.com/integr8ly/workload-web-app/blob/master/Makefile#L9 and adjust the logic on this condition

**Comment by psturc** [comment]
going to verify this on a new cluster

**Review by psturc — APPROVED** [review]
**Verified**

```
/tmp/integreatly-operator/scripts  master ✗                                                                                                                                                                                           54m ⚑
▶ ./podsAz.sh workload-web-app
Pods distribution for 'workload-web-app'
| Pod name | Availability Zone |
| -------- | ----------------- |
| workload-web-app-1-czs2j | us-east-1a |
| workload-web-app-1-deploy | us-east-1b |
| workload-web-app-1-lsrfd | us-east-1c |

/tmp/integreatly-operator/scripts  master ✗                                                                                                                                                                                           54m ⚑
▶ oc get PodDisruptionBudget
NAME                   MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
workload-web-app-pdb   1               N/A               1                     6m20s
```
Screenshot 2020-10-07 at 14 15 02

```
./deploy/undeploy.sh
pod "workload-web-app-1-czs2j" deleted
pod "workload-web-app-1-lsrfd" deleted
service "workload-web-app" deleted
project.project.openshift.io "workload-web-app" deleted
3scale.sh: API_URL=https://3scale-admin.apps.master-4.z1n4.s1.devshift.org/admin/api
3scale.sh: delete workload-app-api-account
3scale.sh: delete workload-app-api service
3scale.sh: delete workload-app-api-backend service
```

**Comment by laurafitzgerald** [comment]
Comments are present that this is verified
/approve

**Pull request merged**
